# Generated by Django 3.0.8 on 2020-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
